import torch
class QNetwork:
    def __int__(self, state_dim, action_size):
        self.state_in = ...
        self.state_out = ...
        self.q_target_in = ...
        action_one_hot = ...

        self.hidden1 = ...
        self.q_state = ...
        self.q_state_action = ...

        self.loss = ...
        self.optimzer = ...

        def update_model(self, session, state, action, q_target):
            feed = ...
            #session.run(self.optimzer, feed_dict = feed_

        def get_q_state(self, session, state):
            q_state = ...
            return q_state